### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-engine-jstransformer#1]
- [x] add badges
- [x] illustrate a setup with a simple base template and some pages (everything in src)
- [x] point to dictionary to specify which extensions map to which jstransformer
- [ ] mention options.filename and the workings of this with partials, helpers etc.

**Comment by nategreen** [comment]
Hello again. So, how *does* one go about adding partials and helpers using "options.filename"? Would that be something like the following?

```js
.use(inPlace({
  engineOptions: {
    hbs: {
      partials: './partials/**/*.hbs'
    }
  }
}))
```

**Comment by ismay** [comment]
Hi @nategreen, that's basically up to how that particular jstransformer wants it (I don't believe it's standardized yet). So for example for [jstransformer-handlebars](https://github.com/jstransformers/jstransformer-handlebars/blob/master/index.js) you can pass partials in options.partials, or helpers in options.helpers (or decorators, see the code).

So:

```
.use(inPlace({
  engineOptions: {
    partials: {
      partialName: partial // haven't tested this, just what I assume from reading the code
    }
  }
}))
```

**Comment by nategreen** [comment]
So, just to make sure I've got it right: in metalsmith-in-place, the `engineOptions` option doesn't pass options to each jstransformer, just to a general pool where the jstransformers can use them?

**Comment by ismay** [comment]
> So, just to make sure I've got it right: in metalsmith-in-place, the engineOptions option doesn't pass options to each jstransformer, just to a general pool where the jstransformers can use them?

Yeah exactly. It seemed the simplest option. If options somehow need to be separated, multiple instances of in-place with filters could be used for that. Maybe in time having per-filetype options will prove to be necessary, but the current setup seems to be enough for the moment.
