### ISSUE TITLE
Documentation on inclusion

### ISSUE THREAD

**Issue by doublejosh** [superwolff/metalsmith-engine-jstransformer#24]
It's unclear how the basic jstransformer engine is used/included within the example.

**Comment by ismay** [comment]
The current documentation can be a bit confusing, but basically you don’t need to install this module manually. It’s included with metalsmith-in-place. See the documentation there.

Also, the upcoming refactor should make this all a lot clearer. And as a final remark, please refrain from using the issues as a help forum. Stackoverflow and the metalsmith slack channel are meant for that.

**Comment by doublejosh** [comment]
Thanks for the reply.  For future travelers...

1. Be sure to install the jstransformer plugin for your template language, eg: jstransformer-handlebars](https://github.com/jstransformers/jstransformer-handlebars)
1. The jstransformer tool relies exclusively on file extension, patterns are merely for exclusion.
